keys:
  - &admin_thijs age1xmqkxszjw6lnehcj6k53wf5ryf7fjcjjhgaquh4hujfr0psv23jqgk62jm 
  - &server_odysseus age1ccthurufgmulxhrk70kneen6eh3gtglpgqvz7kt5nv6av40xkaeqsqz6t5
creation_rules:
  - path_regex: secrets/odysseus/[^/]+\.(yaml|env)$
    key_groups:
    - age:
      - *admin_thijs
      - *server_odysseus
